= Mule Runtime
ifndef::env-github+env-site[]
include::_attributes.adoc[]
endif::[]
:page-id: mule-runtime@3.8::about-mule
:keywords: mule, getting started, transform, message, payload

This guide offers information about how to use link:https://www.mulesoft.org/what-mule-esb[Mule Runtime], commonly called *Mule*, or *Mule ESB* to integrate systems, orchestrate web services and configure the runtime environment. The visual representations of Mule applications you see throughout the documentation are usually depicted as seen in the xref:anypoint-studio@6::about-anypoint-studio#[Anypoint Studio IDE].

== About Mule

*Mule* is the *lightweight integration runtime engine* that allows you to connect anything, anywhere. Rather than creating multiple point-to-point integrations between systems, services, APIs, and devices, you use Mule to create applications that intelligently manage message routing, data mapping, orchestration, reliability, security, and scalability between nodes. Plug other systems and applications into Mule and let it handle communication between systems, allowing you to track and monitor your application ecosystem and external resources.

[NOTE]
Mule is so named because it “carries the heavy load” of developing an infrastructure that supports multiple applications and systems both flexibly and intelligently.

== What is a Mule Application?

Integration developers write Mule applications to tie together various systems. Mule applications are configured to run on Mule runtime to process inbound information, and ingest this information in a pre-defined manner. An expected request to a running Mule application naturally triggers Mule to encode the event and data in a Mule message, passing it along a single thread or multiple threads. Mule transforms and routes the Mule message in stages, according to the processors configured to interact with the message at the various stages. Mule gets the message to its destination, passing the requisite data to the recipient.

The Mule application is defined in an XML document that specifies the necessary dependencies for the Mule application to run. You can configure your Mule application to process data in a variety of ways, and can adjust the Mule runtime instance accordingly. Mule is packaged with components, connectors, and transformers that work quickly to get the data and metadata you need from your Mule application, and feed it to any destination.

== Developing with Mule You Can...

* *Deploy or integrate* applications or systems on premises or in the cloud
* Employ out-of-the-box connectors to create *SaaS integration* applications
* Build and *expose APIs*
* *Consume APIs*
* Create Web services which *orchestrate calls* to other services
* Create interfaces to expose applications for *mobile consumption*
* *Integrate B2B* with solutions that are secure, efficient, and quick to build and deploy
* Shift applications onto the *cloud*
* Connect *B2B e-commerce* activities

== Installation, Management and Deployment

To get started with a local installation of Mule runtime, see xref:install/downloading-and-starting-mule-esb#[Download and Start Mule Runtime].

You can deploy Mule applications to MuleSoft's cloud platform via link://runtime-manager/cloudhub[CloudHub] and manage them via xref:anypoint-platform@latest::runtime-manager:index#[Runtime Manager]. Runtime Manager can be used to manage local deployments as well, making it more versatile than its predecessor xref:mule-management-console@3.8::about-mmc#[Mule Management Console], which is used only for local Mule deployments.

Discover other Mule runtime deployment solutions in the xref:deploy/deploying#[Deploying] section.


== Mule Reference Material

Learn more about Mule features and configuring applications that run on Mule.

* link:/mule-user-guide/v/3.8/reference[Reference]
* xref:api-usage/publishing-and-consuming-apis-with-mule#[Publishing and Consuming APIs with Mule]
* xref:mule-configuration/business-events#[Business Events]
* xref:maven/using-maven-with-mule#[Using Maven with Mule]
* xref:mule-configuration/improving-performance-with-the-kryo-serializer#[Improving Performance with the Kryo Serializer]
* xref:exceptions/error-handling#[Error Handling]
* xref:batch/batch-processing#[Batch Processing]
* xref:transactions/transaction-management#[Transaction Management]
* xref:anypoint-studio@6::adding-and-removing-user-libraries#[Adding and Removing User Libraries]
* xref:shared-resources/domain-project-shared-resources#[Shared Resources]
* xref:mule-configuration/mule-versus-web-application-server#[Mule versus Web Application Server]

////
* xref:security/securing#[Securing Mule Applications]
* xref:debug/debugging#[Debugging Mule Applications]
* xref:testing/testing#[Testing Mule Applications]
* xref:deploy/deploying#[Deploying Mule Applications]
* link:/mule-user-guide/v/3.8/extending[Extending Mule]
////


== See Also

* xref:install/installing#[Install and Run Mule]
* xref:general@master::to-get-anypoint-platform#[Getting Started with Anypoint Platform]
* Understand the link:https://www.mulesoft.com/resources/esb/what-mule-esb[architecture of Mule ESB] in more detail.
* xref:mule-management-console@3.8::setting-up-mmc#[Set up the Mule Management Console]
* xref:anypoint-platform@latest::cloudhub:cloudhub#[Run Mule Applications on CloudHub]
* xref:anypoint-connector-devkit@3.8::about-devkit#[Extend Mule with DevKit]
* xref:mule-concepts#[Learn the basic Mule concepts]
* link:http://training.mulesoft.com[MuleSoft Training]
* link:https://www.mulesoft.com/webinars[MuleSoft Webinars]
* link:http://blogs.mulesoft.com[MuleSoft Blogs]
* link:http://forums.mulesoft.com[MuleSoft Forums]
